/**
 * 许嵩歌单（music/xusong）
 * 仅 mp3+lrc 成对进歌单；封面按专辑映射 coverOf(专辑名)。
 * fileID 来自 assets/xusong.json
 */

const PREFIX =
  'cloud://cloudbase-d7g0orq1z360a029f.636c-cloudbase-d7g0orq1z360a029f-1304836152/music/xusong/'

function coverOf(album) {
  return PREFIX + album + '.jpg'
}

export const XUSONG_PLAYLIST = [
  {
    id: "xs-留香",
    title: "留香",
    artist: '许嵩',
    fileID: PREFIX + "留香.mp3",
    lrcFileID: PREFIX + "留香.lrc",
    coverFileID: coverOf("不如吃茶去"),
  },
  {
    id: "xs-Play-With-Style",
    title: "Play With Style",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-Play With Style.mp3",
    lrcFileID: PREFIX + "许嵩-Play With Style.lrc",
    coverFileID: coverOf("苏格拉没有底"),
  },
  {
    id: "xs-七夕",
    title: "七夕",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-七夕.mp3",
    lrcFileID: PREFIX + "许嵩-七夕.lrc",
    coverFileID: coverOf("不如吃茶去"),
  },
  {
    id: "xs-不煽情",
    title: "不煽情",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-不煽情.mp3",
    lrcFileID: PREFIX + "许嵩-不煽情.lrc",
    coverFileID: coverOf("不如吃茶去"),
  },
  {
    id: "xs-不语",
    title: "不语",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-不语.mp3",
    lrcFileID: PREFIX + "许嵩-不语.lrc",
    coverFileID: coverOf("寻雾启示"),
  },
  {
    id: "xs-亲情式的爱情",
    title: "亲情式的爱情",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-亲情式的爱情.mp3",
    lrcFileID: PREFIX + "许嵩-亲情式的爱情.lrc",
    coverFileID: coverOf("苏格拉没有底"),
  },
  {
    id: "xs-伴虎",
    title: "伴虎",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-伴虎.mp3",
    lrcFileID: PREFIX + "许嵩-伴虎.lrc",
    coverFileID: coverOf("苏格拉没有底"),
  },
  {
    id: "xs-全球变冷",
    title: "全球变冷",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-全球变冷.mp3",
    lrcFileID: PREFIX + "许嵩-全球变冷.lrc",
    coverFileID: coverOf("苏格拉没有底"),
  },
  {
    id: "xs-内线",
    title: "内线",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-内线.mp3",
    lrcFileID: PREFIX + "许嵩-内线.lrc",
    coverFileID: coverOf("自定义"),
  },
  {
    id: "xs-医生",
    title: "医生",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-医生.mp3",
    lrcFileID: PREFIX + "许嵩-医生.lrc",
    coverFileID: coverOf("寻雾启示"),
  },
  {
    id: "xs-千百度",
    title: "千百度",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-千百度.mp3",
    lrcFileID: PREFIX + "许嵩-千百度.lrc",
    coverFileID: coverOf("山水之间"),
  },
  {
    id: "xs-半城烟沙",
    title: "半城烟沙",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-半城烟沙.mp3",
    lrcFileID: PREFIX + "许嵩-半城烟沙.lrc",
    coverFileID: coverOf("半城烟沙"),
  },
  {
    id: "xs-单人旅途",
    title: "单人旅途",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-单人旅途.mp3",
    lrcFileID: PREFIX + "许嵩-单人旅途.lrc",
    coverFileID: coverOf("寻雾启示"),
  },
  {
    id: "xs-叹服",
    title: "叹服",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-叹服.mp3",
    lrcFileID: PREFIX + "许嵩-叹服.lrc",
    coverFileID: coverOf("梦游计"),
  },
  {
    id: "xs-在那不遥远的地方",
    title: "在那不遥远的地方",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-在那不遥远的地方.mp3",
    lrcFileID: PREFIX + "许嵩-在那不遥远的地方.lrc",
    coverFileID: coverOf("不如吃茶去"),
  },
  {
    id: "xs-坏孩子",
    title: "坏孩子",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-坏孩子.mp3",
    lrcFileID: PREFIX + "许嵩-坏孩子.lrc",
    coverFileID: coverOf("寻雾启示"),
  },
  {
    id: "xs-城府",
    title: "城府",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-城府.mp3",
    lrcFileID: PREFIX + "许嵩-城府.lrc",
    coverFileID: coverOf("自定义"),
  },
  {
    id: "xs-多余的解释",
    title: "多余的解释",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-多余的解释.mp3",
    lrcFileID: PREFIX + "许嵩-多余的解释.lrc",
    coverFileID: coverOf("自定义"),
  },
  {
    id: "xs-如果当时",
    title: "如果当时",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-如果当时.mp3",
    lrcFileID: PREFIX + "许嵩-如果当时.lrc",
    coverFileID: coverOf("自定义"),
  },
  {
    id: "xs-如约而至",
    title: "如约而至",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-如约而至.mp3",
    lrcFileID: PREFIX + "许嵩-如约而至.lrc",
    coverFileID: coverOf("如约而至"),
  },
  {
    id: "xs-宇宙之大",
    title: "宇宙之大",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-宇宙之大.mp3",
    lrcFileID: PREFIX + "许嵩-宇宙之大.lrc",
    coverFileID: coverOf("梦游计"),
  },
  {
    id: "xs-对话老师",
    title: "对话老师",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-对话老师.mp3",
    lrcFileID: PREFIX + "许嵩-对话老师.lrc",
    coverFileID: coverOf("不如吃茶去"),
  },
  {
    id: "xs-山水之间",
    title: "山水之间",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-山水之间.mp3",
    lrcFileID: PREFIX + "许嵩-山水之间.lrc",
    coverFileID: coverOf("山水之间"),
  },
  {
    id: "xs-幻听",
    title: "幻听",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-幻听.mp3",
    lrcFileID: PREFIX + "许嵩-幻听.lrc",
    coverFileID: coverOf("苏格拉没有底"),
  },
  {
    id: "xs-庐州月",
    title: "庐州月",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-庐州月.mp3",
    lrcFileID: PREFIX + "许嵩-庐州月.lrc",
    coverFileID: coverOf("自定义"),
  },
  {
    id: "xs-弹指一挥间",
    title: "弹指一挥间",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-弹指一挥间.mp3",
    lrcFileID: PREFIX + "许嵩-弹指一挥间.lrc",
    coverFileID: coverOf("不如吃茶去"),
  },
  {
    id: "xs-微博控",
    title: "微博控",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-微博控.mp3",
    lrcFileID: PREFIX + "许嵩-微博控.lrc",
    coverFileID: coverOf("寻雾启示"),
  },
  {
    id: "xs-心疼你的过去",
    title: "心疼你的过去",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-心疼你的过去.mp3",
    lrcFileID: PREFIX + "许嵩-心疼你的过去.lrc",
    coverFileID: coverOf("寻雾启示"),
  },
  {
    id: "xs-想象之中",
    title: "想象之中",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-想象之中.mp3",
    lrcFileID: PREFIX + "许嵩-想象之中.lrc",
    coverFileID: coverOf("苏格拉没有底"),
  },
  {
    id: "xs-我们的恋爱是对生命的严重浪费",
    title: "我们的恋爱是对生命的严重浪费",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-我们的恋爱是对生命的严重浪费.mp3",
    lrcFileID: PREFIX + "许嵩-我们的恋爱是对生命的严重浪费.lrc",
    coverFileID: coverOf("梦游计"),
  },
  {
    id: "xs-我无所谓",
    title: "我无所谓",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-我无所谓.mp3",
    lrcFileID: PREFIX + "许嵩-我无所谓.lrc",
    coverFileID: coverOf("苏格拉没有底"),
  },
  {
    id: "xs-拆东墙",
    title: "拆东墙",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-拆东墙.mp3",
    lrcFileID: PREFIX + "许嵩-拆东墙.lrc",
    coverFileID: coverOf("梦游计"),
  },
  {
    id: "xs-星座书上",
    title: "星座书上",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-星座书上.mp3",
    lrcFileID: PREFIX + "许嵩-星座书上.lrc",
    coverFileID: coverOf("寻雾启示"),
  },
  {
    id: "xs-有何不可",
    title: "有何不可",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-有何不可.mp3",
    lrcFileID: PREFIX + "许嵩-有何不可.lrc",
    coverFileID: coverOf("自定义"),
  },
  {
    id: "xs-有桃花",
    title: "有桃花",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-有桃花.mp3",
    lrcFileID: PREFIX + "许嵩-有桃花.lrc",
    coverFileID: coverOf("不如吃茶去"),
  },
  {
    id: "xs-梧桐灯",
    title: "梧桐灯",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-梧桐灯.mp3",
    lrcFileID: PREFIX + "许嵩-梧桐灯.lrc",
    coverFileID: coverOf("梦游计"),
  },
  {
    id: "xs-毁人不倦",
    title: "毁人不倦",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-毁人不倦.mp3",
    lrcFileID: PREFIX + "许嵩-毁人不倦.lrc",
    coverFileID: coverOf("梦游计"),
  },
  {
    id: "xs-江湖",
    title: "江湖",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-江湖.mp3",
    lrcFileID: PREFIX + "许嵩-江湖.lrc",
    coverFileID: coverOf("不如吃茶去"),
  },
  {
    id: "xs-河山大好",
    title: "河山大好",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-河山大好.mp3",
    lrcFileID: PREFIX + "许嵩-河山大好.lrc",
    coverFileID: coverOf("苏格拉没有底"),
  },
  {
    id: "xs-清明雨上",
    title: "清明雨上",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-清明雨上.mp3",
    lrcFileID: PREFIX + "许嵩-清明雨上.lrc",
    coverFileID: coverOf("自定义"),
  },
  {
    id: "xs-灰色头像",
    title: "灰色头像",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-灰色头像.mp3",
    lrcFileID: PREFIX + "许嵩-灰色头像.lrc",
    coverFileID: coverOf("寻雾启示"),
  },
  {
    id: "xs-白马非马",
    title: "白马非马",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-白马非马.mp3",
    lrcFileID: PREFIX + "许嵩-白马非马.lrc",
    coverFileID: coverOf("寻雾启示"),
  },
  {
    id: "xs-等到烟火清凉",
    title: "等到烟火清凉",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-等到烟火清凉.mp3",
    lrcFileID: PREFIX + "许嵩-等到烟火清凉.lrc",
    coverFileID: coverOf("不如吃茶去"),
  },
  {
    id: "xs-绝代风华",
    title: "绝代风华",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-绝代风华.mp3",
    lrcFileID: PREFIX + "许嵩-绝代风华.lrc",
    coverFileID: coverOf("绝代风华"),
  },
  {
    id: "xs-胡萝卜须",
    title: "胡萝卜须",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-胡萝卜须.mp3",
    lrcFileID: PREFIX + "许嵩-胡萝卜须.lrc",
    coverFileID: coverOf("梦游计"),
  },
  {
    id: "xs-装糊涂",
    title: "装糊涂",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-装糊涂.mp3",
    lrcFileID: PREFIX + "许嵩-装糊涂.lrc",
    coverFileID: coverOf("苏格拉没有底"),
  },
  {
    id: "xs-认错",
    title: "认错",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-认错.mp3",
    lrcFileID: PREFIX + "许嵩-认错.lrc",
    coverFileID: coverOf("寻雾启示"),
  },
  {
    id: "xs-闺蜜",
    title: "闺蜜",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-闺蜜.mp3",
    lrcFileID: PREFIX + "许嵩-闺蜜.lrc",
    coverFileID: coverOf("苏格拉没有底"),
  },
  {
    id: "xs-降温",
    title: "降温",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-降温.mp3",
    lrcFileID: PREFIX + "许嵩-降温.lrc",
    coverFileID: coverOf("梦游计"),
  },
  {
    id: "xs-隐隐约约",
    title: "隐隐约约",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-隐隐约约.mp3",
    lrcFileID: PREFIX + "许嵩-隐隐约约.lrc",
    coverFileID: coverOf("梦游计"),
  },
  {
    id: "xs-雨幕",
    title: "雨幕",
    artist: '许嵩',
    fileID: PREFIX + "许嵩-雨幕.mp3",
    lrcFileID: PREFIX + "许嵩-雨幕.lrc",
    coverFileID: coverOf("寻雾启示"),
  },
  {
    id: "xs-许嵩_何曼婷-素颜",
    title: "许嵩_何曼婷-素颜",
    artist: '许嵩',
    fileID: PREFIX + "许嵩_何曼婷-素颜.mp3",
    lrcFileID: PREFIX + "许嵩_何曼婷-素颜.lrc",
    coverFileID: coverOf("自定义"),
  },
  {
    id: "xs-许嵩_黄龄-惊鸿一面",
    title: "许嵩_黄龄-惊鸿一面",
    artist: '许嵩',
    fileID: PREFIX + "许嵩_黄龄-惊鸿一面.mp3",
    lrcFileID: PREFIX + "许嵩_黄龄-惊鸿一面.lrc",
    coverFileID: coverOf("不如吃茶去"),
  },
]
