/**
 * 周杰伦无损歌单（music/zjl）
 * flac 播、lrc 唱；文件名不完全一致时写死 lrcFileID，不在运行时猜。
 * 无对应 .lrc 的 flac 不进歌单。
 */
const PREFIX =
  'cloud://cloudbase-d7g0orq1z360a029f.636c-cloudbase-d7g0orq1z360a029f-1304836152/music/zjl/'

export const ZJL_PLAYLIST = [
  {
    id: 'zjl-mojito',
    title: 'Mojito',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - Mojito(2).flac",
    lrcFileID: PREFIX + "周杰伦 - Mojito(1).lrc",
  },
  {
    id: 'zjl-乡间的路',
    title: '乡间的路',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 乡间的路.flac",
    lrcFileID: PREFIX + "12. 乡间的路.lrc",
  },
  {
    id: 'zjl-以父之名',
    title: '以父之名',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 以父之名(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 以父之名(1).lrc",
  },
  {
    id: 'zjl-倒带-live',
    title: '倒带 (Live)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 倒带 (Live)(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 倒带 (Live)(1).lrc",
  },
  {
    id: 'zjl-借口',
    title: '借口',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 借口(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 借口(1).lrc",
  },
  {
    id: 'zjl-半兽人',
    title: '半兽人',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 半兽人(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 半兽人(1).lrc",
  },
  {
    id: 'zjl-告白气球',
    title: '告白气球',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 告白气球(2).flac",
    lrcFileID: PREFIX + "周杰伦 - 告白气球(1).lrc",
  },
  {
    id: 'zjl-外婆',
    title: '外婆',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 外婆(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 外婆(1).lrc",
  },
  {
    id: 'zjl-太阳之子',
    title: '太阳之子',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 太阳之子.flac",
    lrcFileID: PREFIX + "01. 太阳之子.lrc",
  },
  {
    id: 'zjl-威廉古堡',
    title: '威廉古堡',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 威廉古堡.flac",
    lrcFileID: PREFIX + "周杰伦 - 威廉古堡.lrc",
  },
  {
    id: 'zjl-彩虹',
    title: '彩虹',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 彩虹(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 彩虹(1).lrc",
  },
  {
    id: 'zjl-我是如此相信',
    title: '我是如此相信',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 我是如此相信.flac",
    lrcFileID: PREFIX + "周杰伦 - 我是如此相信.lrc",
  },
  {
    id: 'zjl-搁浅',
    title: '搁浅',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 搁浅(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 搁浅(1).lrc",
  },
  {
    id: 'zjl-明明就',
    title: '明明就',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 明明就(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 明明就(1).lrc",
  },
  {
    id: 'zjl-星晴',
    title: '星晴',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 星晴(2).flac",
    lrcFileID: PREFIX + "周杰伦 - 星晴(1).lrc",
  },
  {
    id: 'zjl-晴天',
    title: '晴天',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 晴天(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 晴天(1).lrc",
  },
  {
    id: 'zjl-暗号',
    title: '暗号',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 暗号(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 暗号(1).lrc",
  },
  {
    id: 'zjl-最伟大的作品',
    title: '最伟大的作品',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 最伟大的作品(2).flac",
    lrcFileID: PREFIX + "周杰伦 - 最伟大的作品(1).lrc",
  },
  {
    id: 'zjl-枫',
    title: '枫',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 枫(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 枫(1).lrc",
  },
  {
    id: 'zjl-淘金小镇',
    title: '淘金小镇',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 淘金小镇.flac",
    lrcFileID: PREFIX + "11. 淘金小镇.lrc",
  },
  {
    id: 'zjl-湘女多情',
    title: '湘女多情',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 湘女多情.flac",
    lrcFileID: PREFIX + "04. 湘女多情.lrc",
  },
  {
    id: 'zjl-烟花易冷',
    title: '烟花易冷',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 烟花易冷(2).flac",
    lrcFileID: PREFIX + "周杰伦 - 烟花易冷(1).lrc",
  },
  {
    id: 'zjl-爱在西元前',
    title: '爱在西元前',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 爱在西元前(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 爱在西元前(1).lrc",
  },
  {
    id: 'zjl-米兰的小铁匠',
    title: '米兰的小铁匠',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 米兰的小铁匠(2).flac",
    lrcFileID: PREFIX + "周杰伦 - 米兰的小铁匠(1).lrc",
  },
  {
    id: 'zjl-红尘客栈',
    title: '红尘客栈',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 红尘客栈(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 红尘客栈(1).lrc",
  },
  {
    id: 'zjl-红颜如霜',
    title: '红颜如霜',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 红颜如霜(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 红颜如霜.lrc",
  },
  {
    id: 'zjl-蒲公英的约定',
    title: '蒲公英的约定',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 蒲公英的约定(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 蒲公英的约定(1).lrc",
  },
  {
    id: 'zjl-西西里',
    title: '西西里',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 西西里.flac",
    lrcFileID: PREFIX + "02. 西西里.lrc",
  },
  {
    id: 'zjl-说好不哭-with-五月天阿信',
    title: '说好不哭 (with 五月天阿信)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 说好不哭 (with 五月天阿信).flac",
    lrcFileID: PREFIX + "周杰伦 - 说好不哭 (with 五月天阿信).lrc",
  },
  {
    id: 'zjl-说好的幸福呢',
    title: '说好的幸福呢',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 说好的幸福呢(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 说好的幸福呢(1).lrc",
  },
  {
    id: 'zjl-还在流浪',
    title: '还在流浪',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 还在流浪.flac",
    lrcFileID: PREFIX + "周杰伦 - 还在流浪.lrc",
  },
  {
    id: 'zjl-退后',
    title: '退后',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 退后(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 退后(1).lrc",
  },
  {
    id: 'zjl-黑色毛衣',
    title: '黑色毛衣',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 黑色毛衣(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 黑色毛衣(1).lrc",
  },
  {
    id: 'zjl-龙战骑士',
    title: '龙战骑士',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦 - 龙战骑士(1).flac",
    lrcFileID: PREFIX + "周杰伦 - 龙战骑士(1).lrc",
  },
  {
    id: 'zjl-mine-mine-live',
    title: 'Mine Mine(Live)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-Mine Mine(Live).flac",
    lrcFileID: PREFIX + "周杰伦-Mine Mine(Live).lrc",
  },
  {
    id: 'zjl-不爱我就拉倒',
    title: '不爱我就拉倒',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-不爱我就拉倒.flac",
    lrcFileID: PREFIX + "周杰伦-不爱我就拉倒.lrc",
  },
  {
    id: 'zjl-不能说的秘密-live',
    title: '不能说的秘密(Live)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-不能说的秘密(Live).flac",
    lrcFileID: PREFIX + "周杰伦-不能说的秘密(Live).lrc",
  },
  {
    id: 'zjl-世界末日',
    title: '世界末日',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-世界末日.flac",
    lrcFileID: PREFIX + "周杰伦-世界末日.lrc",
  },
  {
    id: 'zjl-乌克丽丽-live',
    title: '乌克丽丽(Live)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-乌克丽丽(Live).flac",
    lrcFileID: PREFIX + "周杰伦-乌克丽丽(Live).lrc",
  },
  {
    id: 'zjl-你好吗',
    title: '你好吗',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-你好吗.flac",
    lrcFileID: PREFIX + "周杰伦-你好吗.lrc",
  },
  {
    id: 'zjl-听见下雨的声音',
    title: '听见下雨的声音',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-听见下雨的声音.flac",
    lrcFileID: PREFIX + "周杰伦-听见下雨的声音.lrc",
  },
  {
    id: 'zjl-天涯过客',
    title: '天涯过客',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-天涯过客.flac",
    lrcFileID: PREFIX + "周杰伦-天涯过客.lrc",
  },
  {
    id: 'zjl-开不了口-live',
    title: '开不了口(Live)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-开不了口(Live).flac",
    lrcFileID: PREFIX + "周杰伦-开不了口(Live).lrc",
  },
  {
    id: 'zjl-惊叹号-live',
    title: '惊叹号(Live)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-惊叹号(Live).flac",
    lrcFileID: PREFIX + "周杰伦-惊叹号(Live).lrc",
  },
  {
    id: 'zjl-手写的从前',
    title: '手写的从前',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-手写的从前.flac",
    lrcFileID: PREFIX + "周杰伦-手写的从前.lrc",
  },
  {
    id: 'zjl-手语-live',
    title: '手语(Live)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-手语(Live).flac",
    lrcFileID: PREFIX + "周杰伦-手语(Live).lrc",
  },
  {
    id: 'zjl-断了的弦',
    title: '断了的弦',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-断了的弦.flac",
    lrcFileID: PREFIX + "周杰伦-断了的弦.lrc",
  },
  {
    id: 'zjl-最后的战役-live',
    title: '最后的战役(Live)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-最后的战役(Live).flac",
    lrcFileID: PREFIX + "周杰伦-最后的战役(Live).lrc",
  },
  {
    id: 'zjl-水手怕水',
    title: '水手怕水',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-水手怕水.flac",
    lrcFileID: PREFIX + "周杰伦-水手怕水.lrc",
  },
  {
    id: 'zjl-献世-live',
    title: '献世(Live)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-献世(Live).flac",
    lrcFileID: PREFIX + "周杰伦-献世(Live).lrc",
  },
  {
    id: 'zjl-琴伤',
    title: '琴伤',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-琴伤.flac",
    lrcFileID: PREFIX + "周杰伦-琴伤.lrc",
  },
  {
    id: 'zjl-皮影戏',
    title: '皮影戏',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-皮影戏.flac",
    lrcFileID: PREFIX + "周杰伦-皮影戏.lrc",
  },
  {
    id: 'zjl-等你下课-with-杨瑞代',
    title: '等你下课(with 杨瑞代)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-等你下课(with 杨瑞代).flac",
    lrcFileID: PREFIX + "周杰伦-等你下课(with 杨瑞代).lrc",
  },
  {
    id: 'zjl-算什么男人',
    title: '算什么男人',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-算什么男人.flac",
    lrcFileID: PREFIX + "周杰伦-算什么男人.lrc",
  },
  {
    id: 'zjl-美人鱼',
    title: '美人鱼',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-美人鱼.flac",
    lrcFileID: PREFIX + "周杰伦-美人鱼.lrc",
  },
  {
    id: 'zjl-轨迹',
    title: '轨迹',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-轨迹.flac",
    lrcFileID: PREFIX + "周杰伦-轨迹.lrc",
  },
  {
    id: 'zjl-这所有的一切',
    title: '这所有的一切',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-这所有的一切.flac",
    lrcFileID: PREFIX + "周杰伦-这所有的一切.lrc",
  },
  {
    id: 'zjl-迷魂曲',
    title: '迷魂曲',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-迷魂曲.flac",
    lrcFileID: PREFIX + "周杰伦-迷魂曲.lrc",
  },
  {
    id: 'zjl-霍元甲',
    title: '霍元甲',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-霍元甲.flac",
    lrcFileID: PREFIX + "周杰伦-霍元甲.lrc",
  },
  {
    id: 'zjl-鞋子特大号',
    title: '鞋子特大号',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-鞋子特大号.flac",
    lrcFileID: PREFIX + "周杰伦-鞋子特大号.lrc",
  },
  {
    id: 'zjl-龙卷风-live',
    title: '龙卷风(Live)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-龙卷风(Live).flac",
    lrcFileID: PREFIX + "周杰伦-龙卷风(Live).lrc",
  },
  {
    id: 'zjl-龙拳-live',
    title: '龙拳(Live)',
    artist: '周杰伦',
    fileID: PREFIX + "周杰伦-龙拳(Live).flac",
    lrcFileID: PREFIX + "周杰伦-龙拳(Live).lrc",
  },
  {
    id: 'zjl-我要夏天',
    title: '我要夏天',
    artist: '周杰伦、杨瑞代',
    fileID: PREFIX + "周杰伦_杨瑞代-我要夏天.flac",
    lrcFileID: PREFIX + "周杰伦_杨瑞代-我要夏天.lrc",
  },
  {
    id: 'zjl-怎么了',
    title: '怎么了',
    artist: '周杰伦、袁咏琳',
    fileID: PREFIX + "周杰伦_袁咏琳-怎么了.flac",
    lrcFileID: PREFIX + "周杰伦_袁咏琳-怎么了.lrc",
  },
  {
    id: 'zjl-布拉格广场',
    title: '布拉格广场',
    artist: '蔡依林、周杰伦',
    fileID: PREFIX + "蔡依林、周杰伦 - 布拉格广场(1).flac",
    lrcFileID: PREFIX + "蔡依林、周杰伦 - 布拉格广场(1).lrc",
  },
]
